apiVersion: batch/v1
kind: Job
metadata:
  name: service-ticket-train
  namespace: service-ticket
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600

  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-ticket-train
        app.kubernetes.io/component: train
        app.kubernetes.io/part-of: service-ticket-classifier

    spec:
      restartPolicy: OnFailure
      serviceAccountName: service-ticket-job
      containers:
      - name: train
        image: train-ecr-url
        imagePullPolicy: IfNotPresent
        command: ["/app/ml/combine_train.sh"]
      
        envFrom:
        - configMapRef:
            name: service-ticket-job-config
        - secretRef:
            name: service-ticket-db-secret

        resources:
          requests:
              cpu: "250m"
              memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
